# Background {#intro}

Tanzania\index{Tanzania} coastal marine fisheries are largely dominated by artisanal\index{Fisheries!artisanal} fishers [@sobo04], catches are used for subsistence purpose while few species are traded for internal and external markets [@pandu]. The fishery contributes to the social-economic development of the coastal community \index{coastal community} and beyond [@pandu], However, proper management \index{management} of the fishery resource is yet to be realized [@berachi; @pandu; @jacquet]. 

It is widely recognized that knowledge of the status and trends of capture fisheries, including socio-economic aspects, is a key to sound policy-development, better decision-making and responsible fisheries management. For the fisheries to contribute to food security it is important that information related to a particular stock or entire fisheries is available on an instant basis. Fisheries information can be used to validate the policy in place and track the performance of fisheries management. Therefore, the importance of fisheries data collection can not be overemphasized.

Management measures for small-scale fisheries must also account for strategies to collect and analyze data [@robertson]. In many data-poor countries, full stock assessment \index{assessment} is hardly conducted, scientists are forced to use data-poor methods to come up with estimated stock \index{Fisheries!stock} status which in many cases does not reflect the actual situation. For instance, landings of coastal fisheries in Tanzania are chronically under-reported (landings are at least 1.7 times higher than the actual reported landing) and catch rates appear to be maintained by a continual increase in effort [@jacquet; @bush]. Improvement in data collection systems is therefore essential to ensure proper management of the fisheries resource \index{Fisheries!resources}. 

Countries in coastal East Africa have taken up a scheme to decentralized management of the fisheries. The countries have introduced fisheries co-management systems as an approach to manage coastal and marine resources. It is in this context, more accurate and timely information should reach to relevant stakeholders and result in a better-informed decision at all levels. In Tanzania, the system was introduced in the year 2003, it entails establishments of community-based co-management groups commonly known as BMUs (Beach Management Units; Sobo, 2012). Since the inception of the BMUs \index{BMU}, the government, in collaboration with the World Wildlife Fund (WWF) \index{Institutes!WWF} has established more than 204 BMUs along the coast [@kanyange]. One of the major tasks of the BMUs is to participate in fisheries data collection, particularly data related to the Catch Assessment Survey (CAS). The outputs of the CAS are the estimation of the total fish production by weight and value, catch per unit effort, and to conduct stock assessments. 

It was anticipated that participation of BMUs in the data collection would improve coverage and timely collection of the fisheries data. This has been true but challenges are inevitable. One o f the challenges is related to the systems itself, the use of hard copies. BMUs had to collect and send back filled forms to the centralized offices (department of fisheries statistics) for compilation and analysis. This process involved a number of human resources and is time-consuming. However, feedback to the community has been a steep mountain. Following the introduction of smart mobile phones, it was thought, the use of mobile applications in fisheries data collection will facilitate instant submission of catch data to a centralized database, reduce backlog and cost related to the transportation of hard copies and finally facilitate timely feedback to the communities and other stakeholders.  In this context, WWF and Tanzania Fisheries Research Institute (TAFIRI) have been working to realize this concept in the RUMAKI seascape.

In the year 2016, TAFIRI \index{Institutes!TAFIRI} in collaboration with WWF conducted a pilot study on the use of the mobile application in fisheries data collection (e--CAS). The initiative started with selected 5 BMUs, selected members were trained on the use of the mobile application in fisheries data collection. Initial analysis suggested the proof of concept is possible. It was through this initiative species of tuna and tuna-like were recorded for the first time. As of today, the initiative has been rolled out to all coastal districts landing sites and endorsed by the government. 

Monitoring and evaluation of the mobile data collection system have been a work in progress over the years. The monitoring program is meant to fine-tune the application, quality check and provide a recommendation to different stakeholders. At this end, WWF has assigned TAFIRI to undertake analysis of e--CAS and CAS \index{Tools!CAS} fisheries data collected from 2014 to 2018 to assess stock healthiness and quality of the collected fisheries collected from small-scale fisheries landings. Specific tasks under the current agreement are: 

1. To review the status of stock healthiness in the RUMAKI districts based on the data collected from 2014 to 2018. 
2. Compare stock healthiness between RUMAKI and the rest of the coastal districts outside the RUMAKI area. 
3. To provide recommendations on the quality of e--CAS \index{Tools!e--CAS} fisheries data. 
4. To assess the reappearance of fish species in the study area and its link to conservation initiatives. 
5. To prepare a brief summary of the findings for local artisanal fisher communities. 
6. To develop a statistical fact sheet based on the findings 
7. To develop a manual for e--CAS mobile system 
8. To prepare documentation for a stakeholders’ workshop.

The current report is prepared based on the above agreements particularly number 1-4, other deliverables (5-8)  will be submitted as independent documents.
